project:
  type: website
  output-dir: docs 

website:
  title: "Tarefa GC e Visualizadores"
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: House
      - href: about.qmd
        text: about  
      - href: dash_cb.html
        text: Dashboard

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



